### ISSUE TITLE
Melhor experiência com a leitura

### ISSUE THREAD

**Issue by DanielHe4rt** [edersonferreira/zsh4noobs#1]
Salve Ederson, tudo tranquilo?

Enquanto eu lia o conteúdo do repo eu senti muito a falta de comparações de tecnologias parecidas e explicações para iniciantes. Ou como nós chamamos: exemplos de quinta série.

Explique o que cada arquivo faz e porquê você deve mexer e qual é o impacto disso, e também as ferramentas, comandos etc.

Terminando essas alterações eu creio que já estará muito mais didático pra rapaziada que tá querendo acompanhar usando ZSH!

Obrigado!

**Comment by edersonferreira** [comment]
> Salve Ederson, tudo tranquilo?
> 
> Enquanto eu lia o conteúdo do repo eu senti muito a falta de comparações de tecnologias parecidas e explicações para iniciantes. Ou como nós chamamos: exemplos de quinta série.
> 
> Explique o que cada arquivo faz e porquê você deve mexer e qual é o impacto disso, e também as ferramentas, comandos etc.
> 
> Terminando essas alterações eu creio que já estará muito mais didático pra rapaziada que tá querendo acompanhar usando ZSH!
> 
> Obrigado!

Fiz as alterações que foram pedidas, melhorei a explicação, principalmente no "Usando o Zsh", corrigi alguns links quebrados e melhorei a explicação, principalmente porque eu adicionei um tópico específico para o ``~/.zshrc``, espero que agora esteja tudo bem didático!

Abraço

**Comment by edersonferreira** [comment]
Daniel, você viu as mudanças que eu fiz na escrita e nas correções que foram feitas? só quero uma confirmação, pois com isso eu poderei saber se o zsh4noobs está nos conformes para ser aprovado na [he4rt/4noobs](https://github.com/he4rt/4noobs), Obrigado.
