### ISSUE TITLE
Melhor detalhamento na parte da configuração no diretório

### ISSUE THREAD

**Issue by Mooooooov** [edersonferreira/zsh4noobs#2]
O arquivo `~/.zshrc` foi explicado no tópico zshrc mas a parte do comando de como você pode acessar não tá bem claro, eu por exemplo tive dificuldade. Adicionar por exemplo:

`sudo gedit .zshrc` 
ou
`sudo vim .zshrc`

**Comment by edersonferreira** [comment]
Fiz algumas mudanças adicionando detalhes, lembrando que não é necessário usar o sudo, pois o .zshrc está na sua home, logo você tem permissão total nele, dá uma olhada e se estiver bom, fecha essa issue, obrigado.
